title: My testing notes
author: Damian Małecki
description: >- 
  Things that I'm learning about
url: "https://maleckidd.github.io" 
linkedin_username: damian-malecki
github_username: Maleckidd
instagram_username: damian__malecki

# Build settings
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-feed

kramdown:
  input: Kramdown

markdown: kramdown
highlighter: rouge
