title: My testing notes
author: Damian Małecki
description: >- 
  Things that I'm learning about
baseurl: "/Maleckidd.github.io" 
url: "" 
linkedin_username: damian-malecki
github_username: Maleckidd
instagram_username: damian__malecki

# Build settings
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

kramdown:
  input: Kramdown

markdown: kramdown
highlighter: rouge
